export const environment = {
  production: true,
  Admin: "Raju",
  createUser: "/user/createuser",
  loginUser: "/user/login",
  loginAdmin: "/admin/login",
  editUser: "/user/edituser",
  changePassword: "/user/changepassword",
  getMovies: "/admin/getmovies",
  getTheatres: "/admin/gettheatres",
  addMovie: "/admin/addmovie",
  getMovieByMovieName: "/admin/getmovie",
  getTheatreByTheatreId: "/admin/gettheatre",
  getSuggestedMoviesByGenreName: "/admin/getsuggestedmovie",
  updateMovie: "/admin/editmovie",
  deleteMovie: "/admin/removemovie",
  restoreMovie: "/admin/restoremovie",
  getRestoreMovieByMovieName: "/admin/restoremovieByName",
  updateMovieStatus: "/admin/updatestatus",
};